name: CI

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
   
 workflow_dispatch: # allow to run this worklow manually from the Action tab
  # parametize
   inputs:
      VERSION_APP: 
         description: 'version of deployment'
         default: '1.0.3'
         required: true
env:
   APP_NAME: 'fashion-app'
  

     
jobs:
  
  build-and-release: #  This is the name of my job
    runs-on: ubuntu-latest # windows-latest
    steps:
      # Checks-out your github repository
      - uses: actions/checkout@v3

      - name: step name
        run: |
         echo Hello, world!
         echo multi line
         echo "${{ github.event.inputs.VERSION_APP }}"
      
    
    
  
